[project]
name = "trading-service"
version = "0.1.0"
description = "Esqueleto de un sistema de trading automatizado"
authors = [
    {name = "Matias Sosa",email = "matias.sosa@poincenot.com"}
]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "ccxt (>=4.0)",
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn[standard] (>=0.52.4,<0.53.0)"
]


[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=7.0)"
]
